# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cars_owned',
            field=models.ManyToManyField(related_name='user_owner', to='car_app.Car'),
        ),
    ]
